# Generated by Django 3.2.5 on 2021-07-28 12:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('description', models.TextField(blank=True)),
                ('sizes', models.CharField(choices=[('T-SHIRT', [('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('S', 'S')]), ('SHOES', [('45', 45), ('44', 44), ('43', 43), ('42', 42), ('41', 41), ('40', 40), ('39', 39), ('38', 38), ('37', 37), ('36', 36), ('35', 35)])], max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('default', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('SIZE', models.CharField(choices=[('T-SHIRT', [('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('S', 'S')]), ('SHOES', [('45', 45), ('44', 44), ('43', 43), ('42', 42), ('41', 41), ('40', 40), ('39', 39), ('38', 38), ('37', 37), ('36', 36), ('35', 35)])], max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
