# Generated by Django 3.2.5 on 2021-07-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='s',
            field=models.JSONField(choices=[('T-SHIRT', [('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('S', 'S')]), ('SHOES', [('45', 45), ('44', 44), ('43', 43), ('42', 42), ('41', 41), ('40', 40), ('39', 39), ('38', 38), ('37', 37), ('36', 36), ('35', 35)])], default='{}', max_length=100),
        ),
    ]
